Repository IT-s-Okay-to-Lose/BE, pull requests merged in 2025-06, with the labels that each got.

#69 chore : 허용 api 경로 환경변수로 삽입
  src/main/java/com/example/iotl/config/security/PermitAllPathProperties.java
  src/main/java/com/example/iotl/config/security/SecurityConfig.java
  src/main/java/com/example/iotl/filter/JWTFilter.java
  src/main/resources/application.yml
Labels: chore

#71 Fix : 허용 api 경로 및 getter, setter 수정
  .github/ISSUE_TEMPLATE/공통-issue-template.md
  .github/pull_request_template.md
  src/main/java/com/example/iotl/config/security/PermitAllPathProperties.java
  src/main/java/com/example/iotl/config/security/SecurityConfig.java
  src/main/java/com/example/iotl/filter/JWTFilter.java
  src/main/resources/application.yml
Labels: fix

#80 [FEAT] 트랜잭션 비관적 락 적용
  src/main/java/com/example/iotl/entity/Stocks.java
  src/main/java/com/example/iotl/repository/AccountsRepository.java
  src/main/java/com/example/iotl/repository/HoldingsRepository.java
  src/main/java/com/example/iotl/service/OrderService.java
  src/main/java/com/example/iotl/service/TradeService.java
  src/test/java/com/example/iotl/service/OrderServiceTest.java
  src/test/java/com/example/iotl/service/TradeServiceConcurrencyTest.java
Labels: feat
